"""initial schema

Revision ID: c8acae97837e
Revises: 
Create Date: 2026-09-21 09:39:00.177403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8acae97837e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_number', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CLOSED', name='customerstatus'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_city'), 'customers', ['city'], unique=False)
    op.create_index(op.f('ix_customers_customer_number'), 'customers', ['customer_number'], unique=True)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff_name', sa.String(length=100), nullable=False),
    sa.Column('connection_type', sa.Enum('RESIDENTIAL', 'COMMERCIAL', 'INDUSTRIAL', name='connectiontype'), nullable=False),
    sa.Column('minimum_units', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('maximum_units', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate_per_unit', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('fixed_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='tariffstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariffs_connection_type'), 'tariffs', ['connection_type'], unique=False)
    op.create_index(op.f('ix_tariffs_effective_from'), 'tariffs', ['effective_from'], unique=False)
    op.create_index(op.f('ix_tariffs_id'), 'tariffs', ['id'], unique=False)
    op.create_index(op.f('ix_tariffs_status'), 'tariffs', ['status'], unique=False)
    op.create_index(op.f('ix_tariffs_tariff_name'), 'tariffs', ['tariff_name'], unique=False)
    op.create_table('technicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=False),
    sa.Column('availability_status', sa.Enum('AVAILABLE', 'BUSY', 'OFF_DUTY', name='availabilitystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technicians_availability_status'), 'technicians', ['availability_status'], unique=False)
    op.create_index(op.f('ix_technicians_employee_id'), 'technicians', ['employee_id'], unique=True)
    op.create_index(op.f('ix_technicians_id'), 'technicians', ['id'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('connection_number', sa.String(length=50), nullable=False),
    sa.Column('connection_type', sa.Enum('RESIDENTIAL', 'COMMERCIAL', 'INDUSTRIAL', name='connectiontype'), nullable=False),
    sa.Column('sanctioned_load', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tariff_type', sa.String(length=50), nullable=False),
    sa.Column('connection_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISCONNECTED', 'SUSPENDED', name='connectionstatus'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_connection_number'), 'connections', ['connection_number'], unique=True)
    op.create_index(op.f('ix_connections_connection_type'), 'connections', ['connection_type'], unique=False)
    op.create_index(op.f('ix_connections_customer_id'), 'connections', ['customer_id'], unique=False)
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.create_index(op.f('ix_connections_status'), 'connections', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_customer_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['recipient_customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_event_type'), 'notifications', ['event_type'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_customer_id'), 'notifications', ['recipient_customer_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'BILLING_OFFICER', 'FIELD_TECHNICIAN', 'CUSTOMER_SERVICE_AGENT', 'CUSTOMER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('billing_month', sa.String(length=7), nullable=False),
    sa.Column('units_consumed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('energy_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fixed_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('late_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('bill_status', sa.Enum('GENERATED', 'PENDING', 'PAID', 'OVERDUE', 'CANCELLED', name='billstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_bill_status'), 'bills', ['bill_status'], unique=False)
    op.create_index(op.f('ix_bills_billing_month'), 'bills', ['billing_month'], unique=False)
    op.create_index(op.f('ix_bills_connection_id'), 'bills', ['connection_id'], unique=False)
    op.create_index(op.f('ix_bills_id'), 'bills', ['id'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('complaint_type', sa.Enum('POWER_FAILURE', 'VOLTAGE_ISSUE', 'METER_ISSUE', 'BILLING_ISSUE', 'CONNECTION_ISSUE', 'OTHER', name='complainttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'EMERGENCY', name='complaintpriority'), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='complaintstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['technicians.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_assigned_to'), 'complaints', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_complaints_complaint_type'), 'complaints', ['complaint_type'], unique=False)
    op.create_index(op.f('ix_complaints_connection_id'), 'complaints', ['connection_id'], unique=False)
    op.create_index(op.f('ix_complaints_customer_id'), 'complaints', ['customer_id'], unique=False)
    op.create_index(op.f('ix_complaints_id'), 'complaints', ['id'], unique=False)
    op.create_index(op.f('ix_complaints_priority'), 'complaints', ['priority'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_table('meters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('meter_number', sa.String(length=50), nullable=False),
    sa.Column('meter_type', sa.Enum('ANALOG', 'DIGITAL', 'SMART', name='metertype'), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=False),
    sa.Column('initial_reading', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_reading', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('meter_status', sa.Enum('ACTIVE', 'FAULTY', 'REMOVED', name='meterstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meters_connection_id'), 'meters', ['connection_id'], unique=False)
    op.create_index(op.f('ix_meters_id'), 'meters', ['id'], unique=False)
    op.create_index(op.f('ix_meters_meter_number'), 'meters', ['meter_number'], unique=True)
    op.create_index(op.f('ix_meters_meter_status'), 'meters', ['meter_status'], unique=False)
    op.create_table('service_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.Enum('NEW_CONNECTION', 'LOAD_CHANGE', 'METER_REPLACEMENT', 'NAME_CHANGE', 'ADDRESS_CHANGE', 'DISCONNECTION', 'RECONNECTION', name='servicerequesttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'COMPLETED', name='servicerequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requests_connection_id'), 'service_requests', ['connection_id'], unique=False)
    op.create_index(op.f('ix_service_requests_customer_id'), 'service_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_service_requests_id'), 'service_requests', ['id'], unique=False)
    op.create_index(op.f('ix_service_requests_request_type'), 'service_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_service_requests_status'), 'service_requests', ['status'], unique=False)
    op.create_table('complaint_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=255), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_history_complaint_id'), 'complaint_history', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_complaint_history_id'), 'complaint_history', ['id'], unique=False)
    op.create_table('meter_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('previous_reading', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_reading', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('units_consumed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reading_source', sa.Enum('MANUAL', 'SMART_METER', 'FIELD_TECHNICIAN', name='readingsource'), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('billing_period', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meter_readings_billing_period'), 'meter_readings', ['billing_period'], unique=False)
    op.create_index(op.f('ix_meter_readings_id'), 'meter_readings', ['id'], unique=False)
    op.create_index(op.f('ix_meter_readings_meter_id'), 'meter_readings', ['meter_id'], unique=False)
    op.create_index(op.f('ix_meter_readings_reading_date'), 'meter_readings', ['reading_date'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('UPI', 'CARD', 'NET_BANKING', 'WALLET', name='paymentmethod'), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_bill_id'), 'payments', ['bill_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_payment_status'), 'payments', ['payment_status'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_bill_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_meter_readings_reading_date'), table_name='meter_readings')
    op.drop_index(op.f('ix_meter_readings_meter_id'), table_name='meter_readings')
    op.drop_index(op.f('ix_meter_readings_id'), table_name='meter_readings')
    op.drop_index(op.f('ix_meter_readings_billing_period'), table_name='meter_readings')
    op.drop_table('meter_readings')
    op.drop_index(op.f('ix_complaint_history_id'), table_name='complaint_history')
    op.drop_index(op.f('ix_complaint_history_complaint_id'), table_name='complaint_history')
    op.drop_table('complaint_history')
    op.drop_index(op.f('ix_service_requests_status'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_request_type'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_customer_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_connection_id'), table_name='service_requests')
    op.drop_table('service_requests')
    op.drop_index(op.f('ix_meters_meter_status'), table_name='meters')
    op.drop_index(op.f('ix_meters_meter_number'), table_name='meters')
    op.drop_index(op.f('ix_meters_id'), table_name='meters')
    op.drop_index(op.f('ix_meters_connection_id'), table_name='meters')
    op.drop_table('meters')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_priority'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_customer_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_connection_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_complaint_type'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_assigned_to'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_bills_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_connection_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_billing_month'), table_name='bills')
    op.drop_index(op.f('ix_bills_bill_status'), table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_notifications_recipient_customer_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_type'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_connections_status'), table_name='connections')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_customer_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_connection_type'), table_name='connections')
    op.drop_index(op.f('ix_connections_connection_number'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_technicians_id'), table_name='technicians')
    op.drop_index(op.f('ix_technicians_employee_id'), table_name='technicians')
    op.drop_index(op.f('ix_technicians_availability_status'), table_name='technicians')
    op.drop_table('technicians')
    op.drop_index(op.f('ix_tariffs_tariff_name'), table_name='tariffs')
    op.drop_index(op.f('ix_tariffs_status'), table_name='tariffs')
    op.drop_index(op.f('ix_tariffs_id'), table_name='tariffs')
    op.drop_index(op.f('ix_tariffs_effective_from'), table_name='tariffs')
    op.drop_index(op.f('ix_tariffs_connection_type'), table_name='tariffs')
    op.drop_table('tariffs')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_city'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
